namespace SisSo.Pages.Input.Socthda
{
    public class Ct81
    {
        public int Stt { get; set; }        
        public String Stt_rec { get; set; }
        public String Stt_rec0 { get; set; }
        public String Ma_ct { get; set; }
        public DateTime Ngay_ct { get; set; }
        public String So_ct { get; set; }
        public String Ma_kho_i { get; set; }
        public String Ma_vt { get; set; }
        public Decimal So_luong { get; set; }
        public String Ten_kho_i { get; set; }
        public String Ten_kho_i2 { get; set; }
        public String Ten_vt { get; set; }
        public String Ten_vt2 { get; set; }
        public String Ten_tk_vt { get; set; }
        public String Ten_tk_vt2 { get; set; }
        public String Ten_vv_i { get; set; }
        public String Ten_vv_i2 { get; set; }
        public Decimal Ton13 { get; set; }
        public Decimal Sua_tk_vt { get; set; }
        public Decimal Gia_ton { get; set; }
        public Decimal Sl_min { get; set; }
        public String Tk_gv_dmvt { get; set; }
        public String Tk_dt_dmvt { get; set; }
        public String Tk_ck_dmvt { get; set; }
        public String Tk_vt_dmvt { get; set; }
        public Decimal Vt_ton_kho { get; set; }
        public String Tk_km_dmvt { get; set; }
        public String Dvt { get; set; }
        public Decimal Stt_dong { get; set; }
        public String Km_ck { get; set; }
        public String Tk_km_i { get; set; }
        public String Ma_px_i { get; set; }
        public DateTime? Ngay_ct_tc { get; set; }
        public String So_ct_tc { get; set; }
        public String Ma_hdm_i { get; set; }
        public String Ma_tb_i { get; set; }
        public String Ma_ns_i { get; set; }
        public String Gc0_i { get; set; }
        public String Ma_s2_i { get; set; }
        public String Ma_s1_i { get; set; }
        public Decimal Sl_s2_i { get; set; }
        public Decimal Sl_s1_i { get; set; }
        public String Gc_s2_i { get; set; }
        public String Gc_s1_i { get; set; }
        public DateTime? Ngay_s2_i { get; set; }
        public DateTime? Ngay_s1_i { get; set; }
        public String Ma_ku_i { get; set; }
        public String Ma_hd_i { get; set; }
        public String Ma_bpht_i { get; set; }
        public Decimal So_luong2 { get; set; }
        public String Dvt2 { get; set; }
        public String Loc_id { get; set; }
        public String Ma_nvhh { get; set; }
        public DateTime? Han_sd_lot { get; set; }
        public String Lot_nbr { get; set; }
        public String So_dh_i { get; set; }
        public string Ma_dh_i { get; set; }
        public String So_lsx_i { get; set; }
        public String Ma_phi_i { get; set; }
        public Decimal Sl_sp { get; set; }
        public String Ma_sp { get; set; }
        public String Tk_thue_i { get; set; }
        public String Gc_td3_i { get; set; }
        public String Gc_td2_i { get; set; }
        public String Gc_td1_i { get; set; }
        public Decimal Sl_td3_i { get; set; }
        public Decimal Sl_td2_i { get; set; }
        public Decimal Sl_td1_i { get; set; }
        public DateTime? Ngay_td1_i { get; set; }
        public String Ma_td3_i { get; set; }
        public String Ma_td2_i { get; set; }
        public String Stt_rec0pn { get; set; }
        public String Stt_rec_pn { get; set; }
        public String Ma_td_i { get; set; }
        public String Ma_vv_i { get; set; }
        public String Tk_ck { get; set; }
        public String Tk_dt { get; set; }
        public String Tk_gv { get; set; }
        public String Tk_vt { get; set; }
        public Decimal Ck_nt { get; set; }
        public Decimal Ck { get; set; }
        public Decimal Tl_ck { get; set; }
        public Decimal Thue_nt { get; set; }
        public Decimal Thue { get; set; }
        public Decimal Tien2 { get; set; }
        public Decimal Tien_nt2 { get; set; }
        public Decimal Gia2 { get; set; }
        public Decimal Gia_nt2 { get; set; }
        public Decimal Tien { get; set; }
        public Decimal Tien_nt { get; set; }
        public Decimal Gia { get; set; }
        public Decimal Gia_nt { get; set; }
        public Decimal He_so1 { get; set; }
        public String Dvt1 { get; set; }
        public Decimal So_luong1 { get; set; }
        public Decimal Sl_qd { get; set; }
        public Decimal Gia_qd_nt { get; set; }
        public Decimal Gia_qd { get; set; }
        public Decimal Gia_qd_nt2 { get; set; }
        public Decimal Gia_qd2 { get; set; }
        public String Dvt_qd { get; set; }
        public String Ma_td4_i { get; set; }
        public String Nh_vt1 { get; set; }
        public String Nh_vt2 { get; set; }
        public String Nh_vt3 { get; set; }
        public String Tk_gg_dmvt { get; set; }
        public String Ma_lo { get; set; }
        public DateTime? Ngay_hh { get; set; }
        public String Ma_nh_km { get; set; }
        public Decimal Tien_km_nt { get; set; }
        public Decimal Tien_km { get; set; }
        public Decimal Pt_km { get; set; }
        public String Ma_ctkm { get; set; }
        public Boolean Khuyen_mai { get; set; }
        public String Ma_hdcr_i { get; set; }
        public String Stt_rec1 { get; set; }
        public Decimal Ty_gia { get; set; }
        public string Ma_nt0 { get; set; }
        public string Ma_thue_i { get; set; }
        public Decimal Thue_suat_i { get; set; }
        public string Dien_giaii { get; set; }
    }
}
