namespace SisSo.Pages.Input.Socthda
{
    public class Ph81
    {
        public String Stt_rec { get; set; }
        public String Ma_ct { get; set; }
        public DateTime Ngay_ct { get; set; }
        public DateTime Ngay_lct { get; set; }
        public String Ma_gd { get; set; }
        public String So_ct { get; set; }
        public String Ma_kh { get; set; }
        public String Ten_kh { get; set; }
        public String Ten_kh2 { get; set; }
        public String Ong_ba { get; set; }
        public String Dien_giai { get; set; }
        public Decimal T_so_luong { get; set; }
        public String Ma_nt { get; set; }
        public Decimal Ty_gia { get; set; }
        public Decimal T_tien_nt { get; set; }
        public Decimal T_tien { get; set; }
        public String Ma_thue { get; set; }
        public Decimal T_thue_nt { get; set; }
        public Decimal T_thue { get; set; }
        public Decimal Sua_thue { get; set; }
        public String Ma_kh2 { get; set; }
        public String Tk_thue_co { get; set; }
        public String Tk_thue_no { get; set; }
        public Decimal Sua_tkthue { get; set; }
        public Decimal T_tien_nt2 { get; set; }
        public Decimal T_tien2 { get; set; }
        public Decimal Tinh_ck { get; set; }
        public String Tk_ck { get; set; }
        public Decimal T_ck_nt { get; set; }
        public Decimal T_ck { get; set; }
        public Decimal Han_tt { get; set; }
        public Decimal T_tt_nt { get; set; }
        public Decimal T_tt { get; set; }
        public DateTime? Date { get; set; }
        public String Time { get; set; }
        public Int32 User_id { get; set; }
        public DateTime? Date0 { get; set; }
        public Decimal Sua_tien { get; set; }
        public String Ma_qs { get; set; }
        public String Ws_id { get; set; }        
        public String Time0 { get; set; }
        public Int32 User_id0 { get; set; }
        public String Status { get; set; }
        public String Loai_ct { get; set; }
        public String Ma_dvcs { get; set; }
        public Decimal Ty_giaf { get; set; }
        public String Ma_nx { get; set; }
        public String Ten_nx { get; set; }
        public String Ten_nx2 { get; set; }
        public String User_name { get; set; }
        public String So_seri { get; set; }
        public String Ten_vtthue { get; set; }
        public String Dia_chi { get; set; }
        public String Ma_so_thue { get; set; }
        public Decimal Du13 { get; set; }
        public String Ten_gd { get; set; }
        public String Ten_gd2 { get; set; }
        public String Ma_bp { get; set; }
        public String Ten_bp { get; set; }
        public String Ten_bp2 { get; set; }
        public String Px_gia_dd { get; set; }
        public Decimal Thue_suat { get; set; }
        public String So_cttmp { get; set; }
        public String Ma_qstmp { get; set; }
        public Decimal T_tien_sau_ck { get; set; }
        public Decimal T_tien_sau_ck_nt { get; set; }
        public Decimal Tk_thue_co_cn { get; set; }
        public String So_dh { get; set; }
        public String Ghi_chu0 { get; set; }
        public String Gc_thue { get; set; }
        public String Ma_so_thue_dmkh { get; set; }
        public String Tk_thue_co_dmthue { get; set; }
        public Int32 Sl_in { get; set; }
        public String Ht_tt { get; set; }
        public String Tk_nh { get; set; }
        public String Ten_post { get; set; }
        public String Ma_thck { get; set; }
        public String Mau_hd { get; set; }
        public Decimal So_ct1 { get; set; }
        public Decimal So_ct2 { get; set; }
        public String Transform { get; set; }
        public String Ten_dn_in { get; set; }
        public String Mst_dn_in { get; set; }
        public Int32 So_lien_hd { get; set; }
        public String Ten_lien1 { get; set; }
        public String Ten_lien2 { get; set; }
        public String Ten_lien3 { get; set; }
        public String Ten_lien4 { get; set; }
        public String Ten_lien5 { get; set; }
        public String Ten_lien6 { get; set; }
        public String Ten_lien7 { get; set; }
        public String Ten_lien8 { get; set; }
        public String Ten_lien9 { get; set; }
        public String Ten_act { get; set; }
        public String Ma_file { get; set; }
        public String Ten_act2 { get; set; }
        public String Ten_post2 { get; set; }
        public String Loai_tg { get; set; }
        public String Ten_kh_thue { get; set; }
        public String Nh_kh3 { get; set; }
        public Decimal T_sl_qd { get; set; }
        public String Expr1 { get; set; }
        public Decimal Loai_tk_co { get; set; }
        public String Kh_mau_hd { get; set; }
        public String Stt_rec_pt { get; set; }
        public String So_ct_pt { get; set; }
        public String Ma_ct_pt { get; set; }       
        public int Loai_xnvl { get; set; }
        public String Ma_qs_pt { get; set; }
        public String Hd_thue { get; set; }
        public String User_name0 { get; set; }
        public String So_hdg { get; set; }
        public String Ten_dv_vc { get; set; }
        public DateTime? Ngay_hdg { get; set; }
        public String Dia_chi_gh { get; set; }
        public String Dia_chi_nh { get; set; }
        public String So_vd { get; set; }
        public String So_con { get; set; }
        public Decimal T_sl_km { get; set; }
        public Decimal T_tien_km_nt { get; set; }
        public Decimal T_tien_km { get; set; }
        public Decimal T_thue_km_nt { get; set; }
        public Decimal T_thue_km { get; set; }
        public Decimal Tien_tc_nt { get; set; }
        public Decimal Tien_tc { get; set; }
        public Decimal T_tt_km_nt { get; set; }
        public Decimal T_tt_km { get; set; }
        public Int32 Co_km { get; set; }
        public String Dien_thoai { get; set; }
        public int Tinh_trang_hddt { get; set; }
        public String So_ct_hddt { get; set; }
        public String So_seri_hddt { get; set; }
        public String Mau_hddt { get; set; }
        public String Inv_guid { get; set; }
        public Decimal Sd_hddt_yn { get; set; }
        public String Ten_tinh_trang { get; set; }
        public String Ten_tinh_trang2 { get; set; }
        public String E_mail { get; set; }
        public String So_ctf { get; set; }
        public String Ten_nh { get; set; }
        public String Order_id { get; set; }
        public String Responsecode { get; set; }
        public String Ma_ctkm { get; set; }
        public Decimal Tien_km { get; set; }
        public Decimal Tien_km_nt { get; set; }
        public String Stt_rec1 { get; set; }
        public string Ma_dvcs_bl { get; set; }
        public string So_the { get; set; }
        public string Stt_rec_px { get; set; }
        public string Ma_ct_px { get; set; }
        public string So_ct_px { get; set; }
        public string Ma_qs_px { get; set; }
        public string Stt_rec_pnd { get; set; }
        public string Ma_ct_pnd { get; set; }
        public string So_ct_pnd { get; set; }
        public string Ma_qs_pnd { get; set; }
    }
}
