namespace SisSo.Pages.Input.Cactpt1
{
    public class Ph41
    {
        public String Stt_rec { get; set; }
        public String Ma_dvcs { get; set; }
        public String Ma_ct { get; set; }
        public String Ma_nk { get; set; }
        public String Ma_gd { get; set; }
        public DateTime Ngay_ct { get; set; }
        public DateTime Ngay_lct { get; set; }
        public String So_ct { get; set; }
        public String So_lo { get; set; }
        public DateTime? Ngay_lo { get; set; }
        public String Ma_kh { get; set; }
        public String Dia_chi { get; set; }
        public String Ong_ba { get; set; }
        public String Dien_giai { get; set; }
        public String Tk { get; set; }
        public String Ma_ku { get; set; }
        public String Ma_nt { get; set; }
        public Decimal Ty_gia { get; set; }
        public Decimal Ty_gia_ht { get; set; }
        public Decimal Sua_tggs { get; set; }
        public Decimal T_tien_nt { get; set; }
        public Decimal T_tien { get; set; }
        public Decimal T_thue_nt { get; set; }
        public Decimal T_thue { get; set; }
        public Decimal T_tt_nt { get; set; }
        public Decimal T_tt { get; set; }
        public String So_ct_tt { get; set; }
        public DateTime? Date { get; set; }
        public String Time { get; set; }
        public Int32 User_id { get; set; }
        public DateTime? Date0 { get; set; }
        public String Time0 { get; set; }
        public Int32 User_id0 { get; set; }
        public String Status { get; set; }
        public String So_lo1 { get; set; }
        public String Ma_bpht { get; set; }
        public String Loai_ct { get; set; }
        public String So_lsx { get; set; }
        public String So_dh { get; set; }
        public String Ma_td1 { get; set; }
        public String Ma_td2 { get; set; }
        public String Ma_td3 { get; set; }
        public DateTime? Ngay_td1 { get; set; }
        public DateTime? Ngay_td2 { get; set; }
        public DateTime? Ngay_td3 { get; set; }
        public Decimal Sl_td1 { get; set; }
        public Decimal Sl_td2 { get; set; }
        public Decimal Sl_td3 { get; set; }
        public String Gc_td1 { get; set; }
        public String Gc_td2 { get; set; }
        public String Gc_td3 { get; set; }
        public String Ma_hd { get; set; }
        public Decimal Sua_tt_ck { get; set; }
        public Decimal Sua_tien { get; set; }
        public DateTime? Ngay_s1 { get; set; }
        public DateTime? Ngay_s2 { get; set; }
        public String Gc_s1 { get; set; }
        public String Gc_s2 { get; set; }
        public Decimal Sl_s1 { get; set; }
        public Decimal Sl_s2 { get; set; }
        public String Ma_s1 { get; set; }
        public String Ma_s2 { get; set; }
        public String Ma_tb { get; set; }
        public String Ma_hdm { get; set; }
        public Decimal Han_tt { get; set; }
        public String Ma_px { get; set; }
        public String Ma_qs { get; set; }
        public String Dgiai_ct { get; set; }
        public Decimal Ty_giaf { get; set; }
        public Decimal Ty_gia_htf { get; set; }
        public Decimal So_ct_kem { get; set; }
        public Int32 Row_id { get; set; }
        public String Ws_id { get; set; }
        public String Ghi_chu0 { get; set; }
        public String Stt_rec_hd { get; set; }
        public String Hd_thue { get; set; }
        public Decimal T_tien_cltg { get; set; }
        public Decimal T_tien_tt { get; set; }
        public Int32 Theo_doi_pt { get; set; }
        public String Files_dinhkem { get; set; }
        public String Ma_so_thue { get; set; }
        public Decimal Du13 { get; set; }

    }
}
