namespace SisSo.Pages.Input.Sodmhdb
{
    public class Dmhdct
    {
        public int Stt { get; set; }
        public String Ma_hd { get; set; }
        public String Loai_hd { get; set; }
        public DateTime? Ngay_hd1 { get; set; }
        public DateTime? Ngay_hd2 { get; set; }
        public String Ma_kh { get; set; }
        public String Dien_giai { get; set; }
        public String Ma_ct { get; set; }
        public String Ma_vt { get; set; }
        public Decimal Sl_hd { get; set; }
        public Decimal Sl_th { get; set; }
        public Decimal Gia_nt { get; set; }
        public Decimal Gia { get; set; }
        public Decimal Tien_nt { get; set; }
        public Decimal Tien { get; set; }
        public String Stt_rec { get; set; }
        public String Stt_rec0 { get; set; }
        public DateTime Ngay_ct { get; set; }
        public String So_ct { get; set; }
        public String Ma_kho_i { get; set; }
        public Decimal So_luong { get; set; }
        public Decimal So_luong1 { get; set; }
        public String Dvt1 { get; set; }
        public Decimal He_so1 { get; set; }
        public Decimal Gia_nt2 { get; set; }
        public Decimal Gia2 { get; set; }
        public Decimal Tien_nt2 { get; set; }
        public Decimal Tien2 { get; set; }
        public String Ma_thue { get; set; }
        public Decimal Thue_suat { get; set; }
        public Decimal Thue { get; set; }
        public Decimal Thue_nt { get; set; }
        public Decimal Tl_ck { get; set; }
        public Decimal Ck { get; set; }
        public Decimal Ck_nt { get; set; }
        public String Tk_vt { get; set; }
        public String Tk_gv { get; set; }
        public String Tk_dt { get; set; }
        public String Tk_ck { get; set; }
        public String Ma_vv_i { get; set; }
        public String Ma_td_i { get; set; }
        public String Stt_rec_pn { get; set; }
        public String Stt_rec0pn { get; set; }
        public String Ma_td2_i { get; set; }
        public String Ma_td3_i { get; set; }
        public DateTime? Ngay_td1_i { get; set; }
        public Decimal Sl_td1_i { get; set; }
        public Decimal Sl_td2_i { get; set; }
        public Decimal Sl_td3_i { get; set; }
        public String Gc_td1_i { get; set; }
        public String Gc_td2_i { get; set; }
        public String Gc_td3_i { get; set; }
        public String Tk_thue_i { get; set; }
        public String Ma_sp { get; set; }
        public Decimal Sl_sp { get; set; }
        public String Ma_phi_i { get; set; }
        public String So_lsx_i { get; set; }
        public String So_dh_i { get; set; }
        public String Lot_nbr { get; set; }
        public DateTime? Han_sd_lot { get; set; }
        public String Ma_nvhh { get; set; }
        public String Loc_id { get; set; }
        public String Dvt2 { get; set; }
        public Decimal So_luong2 { get; set; }
        public String Ma_bpht_i { get; set; }
        public String Ma_hd_i { get; set; }
        public String Ma_ku_i { get; set; }
        public DateTime? Ngay_s1_i { get; set; }
        public DateTime? Ngay_s2_i { get; set; }
        public String Gc_s1_i { get; set; }
        public String Gc_s2_i { get; set; }
        public Decimal Sl_s1_i { get; set; }
        public Decimal Sl_s2_i { get; set; }
        public String Ma_s1_i { get; set; }
        public String Ma_s2_i { get; set; }
        public String Gc0_i { get; set; }
        public String Ma_ns_i { get; set; }
        public String Ma_tb_i { get; set; }
        public String Ma_hdm_i { get; set; }
        public String So_ct_tc { get; set; }
        public DateTime? Ngay_ct_tc { get; set; }
        public String Ma_px_i { get; set; }
        public DateTime? Han_gh_i { get; set; }
        public String Ma_msx_i { get; set; }
        public String Ma_baobi { get; set; }
        public String Co_hat { get; set; }
        public String Tl_pd { get; set; }
        public String Do_trang { get; set; }
        public String Do_sang { get; set; }
        public String Ghi_chu_i { get; set; }
        public String Tap_chat { get; set; }
        public String Tem { get; set; }
        public String Xep_pallet { get; set; }
        public Decimal So_tui { get; set; }
        public Decimal So_tui_cont { get; set; }
        public String Ma_pallet { get; set; }
        public Decimal Sl_bao { get; set; }
        public Decimal Sl_pallet { get; set; }
        public String Pallet { get; set; }
        public String Ma_botda { get; set; }
        public String Ma_ca_pallet { get; set; }
        public String Ma_ca_cont { get; set; }
        public String Ma_bia_carton { get; set; }
        public Decimal Sl_bia_carton { get; set; }
        public String Ma_mang_co { get; set; }
        public Decimal Sl_mang_co { get; set; }
        public String Ma_chi_may { get; set; }
        public Decimal Sl_chi_may { get; set; }
        public String Ma_tam_lot { get; set; }
        public Decimal Sl_tam_lot { get; set; }
        public String Stt_rec0_psx { get; set; }
        public string Ma_dvcs_bl { get; set; }
        public Decimal Vt_ton_kho { get; set; }
        public Decimal Ton13 { get; set; }
        public String Ma_lo { get; set; }
        public String Ten_vt { get; set; }


    }
}
