namespace SisSo.Pages.Input.Cactbc1
{
    public class Ct51
    {
        public int Stt { get; set; }
        public String Stt_rec { get; set; }
        public String Stt_rec0 { get; set; }
        public String Ma_ct { get; set; }
        public DateTime Ngay_ct { get; set; }
        public String So_ct { get; set; }
        public String Dien_giai_i { get; set; }
        public String Tk_i { get; set; }
        public Decimal Tien_nt { get; set; }
        public Decimal Tien { get; set; }
        public String Ma_kh_i { get; set; }
        public String Ma_vv_i { get; set; }
        public String Ma_td_i { get; set; }
        public Decimal Tt_qd { get; set; }
        public String Stt_rec_tt { get; set; }
        public String Ma_thue_i { get; set; }
        public Decimal Thue_suati { get; set; }
        public String Tk_thue_i { get; set; }
        public Decimal Thue { get; set; }
        public Decimal Thue_nt { get; set; }
        public Decimal Tt { get; set; }
        public Decimal Tt_nt { get; set; }
        public DateTime? Ngay_ct0 { get; set; }
        public String So_seri0 { get; set; }
        public String So_ct0 { get; set; }
        public String Ma_td2_i { get; set; }
        public String Ma_td3_i { get; set; }
        public DateTime? Ngay_td1_i { get; set; }
        public Decimal Sl_td1_i { get; set; }
        public Decimal Sl_td2_i { get; set; }
        public Decimal Sl_td3_i { get; set; }
        public String Gc_td1_i { get; set; }
        public String Gc_td2_i { get; set; }
        public String Gc_td3_i { get; set; }
        public String Ma_sp { get; set; }
        public Decimal Sl_sp { get; set; }
        public String Ma_phi_i { get; set; }
        public String So_lsx_i { get; set; }
        public String So_dh_i { get; set; }
        public String Ma_bpht_i { get; set; }
        public String Ma_hd_i { get; set; }
        public String Ma_ku_i { get; set; }
        public Decimal Ty_gia_ht2 { get; set; }
        public Decimal Tien_tt { get; set; }
        public DateTime? Ngay_s1_i { get; set; }
        public DateTime? Ngay_s2_i { get; set; }
        public String Gc_s1_i { get; set; }
        public String Gc_s2_i { get; set; }
        public Decimal Sl_s1_i { get; set; }
        public Decimal Sl_s2_i { get; set; }
        public String Ma_s1_i { get; set; }
        public String Ma_s2_i { get; set; }
        public String Gc0_i { get; set; }
        public String Ma_ns_i { get; set; }
        public String Ma_tb_i { get; set; }
        public String Ma_hdm_i { get; set; }
        public String So_ct_tc { get; set; }
        public DateTime? Ngay_ct_tc { get; set; }
        public String Ma_nvhh { get; set; }
        public String Lot_nbr { get; set; }
        public DateTime? Han_sd_lot { get; set; }
        public String Loc_id { get; set; }
        public String Dvt2 { get; set; }
        public Decimal So_luong2 { get; set; }
        public String Ma_px_i { get; set; }
        public Decimal Ty_giahtf2 { get; set; }
        public Decimal Stt_dong { get; set; }
        public String Ma_nt_i { get; set; }
        public Decimal T_tt_nt0 { get; set; }
        public Decimal T_tt_qd { get; set; }
        public Decimal Phai_tt_nt { get; set; }
        public Decimal Phai_tt_nt2 { get; set; }
        public String Ma_td4_i { get; set; }
        public Decimal Tien_cltg { get; set; }
        public String Hd_pl { get; set; }
        public String Loai_hd { get; set; }
        public String Marketing { get; set; }
        public String Kinh_doanh { get; set; }
        public String Trien_khai { get; set; }
        public String Lap_trinh { get; set; }
        public String Ctv { get; set; }
        public String Loai_hdong { get; set; }
        public String Ten_tk_i { get; set; }
        public String Ten_kh_i { get; set; }


    }
}
