namespace SisSo.Pages.Input.Sobg1
{
    public class Ct101
    {
        public String Ten_vt { get; set; }
        public int Stt { get; set; }
        public String Ma_hd { get; set; }
        public String Loai_hd { get; set; }
        public DateTime? Ngay_hd1 { get; set; }
        public DateTime? Ngay_hd2 { get; set; }
        public String Ma_kh { get; set; }
        public String Dien_giai { get; set; }
        public String Ma_ct { get; set; }
        public String Ma_vt { get; set; }
        public Decimal Sl_hd { get; set; }
        public Decimal Sl_th { get; set; }
        public Decimal Gia_nt { get; set; }
        public Decimal Gia { get; set; }
        public Decimal Tien_nt { get; set; }
        public Decimal Tien { get; set; }
        public String Stt_rec { get; set; }
        public String Stt_rec0 { get; set; }
        public DateTime? Ngay_ct { get; set; }
        public String So_ct { get; set; }
        public String Ma_kho_i { get; set; }
        public Decimal So_luong { get; set; }
        public Decimal So_luong1 { get; set; }
        public String Dvt1 { get; set; }
        public Decimal He_so1 { get; set; }
        public Decimal Gia_nt2 { get; set; }
        public Decimal Gia2 { get; set; }
        public Decimal Tien_nt2 { get; set; }
        public Decimal Tien2 { get; set; }
        public String Ma_thue { get; set; }
        public Decimal Thue_suat { get; set; }
        public Decimal Thue { get; set; }
        public Decimal Thue_nt { get; set; }
        public Decimal Tl_ck { get; set; }
        public Decimal Ck { get; set; }
        public Decimal Ck_nt { get; set; }
        public String Tk_vt { get; set; }
        public String Tk_gv { get; set; }
        public String Tk_dt { get; set; }
        public String Tk_ck { get; set; }
        public String Ma_vv_i { get; set; }
        public String Ma_td_i { get; set; }
        public String Stt_rec_pn { get; set; }
        public String Stt_rec0pn { get; set; }
        public String Ma_td2_i { get; set; }
        public String Ma_td3_i { get; set; }
        public DateTime? Ngay_td1_i { get; set; }
        public Decimal Sl_td1_i { get; set; }
        public Decimal Sl_td2_i { get; set; }
        public Decimal Sl_td3_i { get; set; }
        public String Gc_td1_i { get; set; }
        public String Gc_td2_i { get; set; }
        public String Gc_td3_i { get; set; }
        public String Tk_thue_i { get; set; }
        public String Ma_sp { get; set; }
        public Decimal Sl_sp { get; set; }
        public String Ma_phi_i { get; set; }
        public String So_lsx_i { get; set; }
        public String So_dh_i { get; set; }
        public String Lot_nbr { get; set; }
        public DateTime? Han_sd_lot { get; set; }
        public String Ma_nvhh { get; set; }
        public String Loc_id { get; set; }
        public String Dvt2 { get; set; }
        public Decimal So_luong2 { get; set; }
        public String Ma_bpht_i { get; set; }
        public String Ma_hd_i { get; set; }
        public String Ma_ku_i { get; set; }
        public DateTime? Ngay_s1_i { get; set; }
        public DateTime? Ngay_s2_i { get; set; }
        public String Gc_s1_i { get; set; }
        public String Gc_s2_i { get; set; }
        public Decimal Sl_s1_i { get; set; }
        public Decimal Sl_s2_i { get; set; }
        public String Ma_s1_i { get; set; }
        public String Ma_s2_i { get; set; }
        public String Gc0_i { get; set; }
        public String Ma_ns_i { get; set; }
        public String Ma_tb_i { get; set; }
        public String Ma_hdm_i { get; set; }
        public String So_ct_tc { get; set; }
        public DateTime? Ngay_ct_tc { get; set; }
        public String Ma_px_i { get; set; }
        public DateTime? Han_gh_i { get; set; }
        public Decimal Tg_baohanh { get; set; }
        public String Status_name { get; set; }
        public String Status_name2 { get; set; }
        public Boolean Duyet { get; set; }

    }
}
