namespace SisSo.Pages.Input.Sobg1
{
    public class Ph101
    {
        public String Ma_hd { get; set; }
        public String Loai_hd { get; set; }
        public String So_hd { get; set; }
        public String Ma_bp { get; set; }
        public String Ma_bpht { get; set; }
        public String Ma_kh { get; set; }
        public DateTime? Ngay_ky { get; set; }
        public DateTime? Ngay_ht { get; set; }
        public DateTime? Ngay_hd1 { get; set; }
        public DateTime? Ngay_hd2 { get; set; }
        public String Dien_giai { get; set; }
        public String Dien_giai2 { get; set; }
        public String Ma_ct { get; set; }
        public String Status { get; set; }
        public String Status2 { get; set; }
        public String Ma_nt { get; set; }
        public Decimal Tien_nt { get; set; }
        public Decimal Tien { get; set; }
        public String Nh_hd1 { get; set; }
        public String Nh_hd2 { get; set; }
        public String Nh_hd3 { get; set; }
        public String Ghi_chu { get; set; }
        public DateTime? Date { get; set; }
        public String Time { get; set; }
        public DateTime? Date0 { get; set; }
        public String Time0 { get; set; }
        public Int32 User_id0 { get; set; }
        public String Ma_td1 { get; set; }
        public String Ma_td2 { get; set; }
        public String Ma_td3 { get; set; }
        public DateTime? Ngay_td1 { get; set; }
        public DateTime? Ngay_td2 { get; set; }
        public DateTime? Ngay_td3 { get; set; }
        public Decimal Sl_td1 { get; set; }
        public Decimal Sl_td2 { get; set; }
        public Decimal Sl_td3 { get; set; }
        public String Gc_td1 { get; set; }
        public String Gc_td2 { get; set; }
        public String Gc_td3 { get; set; }
        public String Ma_tra_cuu { get; set; }
        public String Ma_hd_me { get; set; }
        public String Ma_vv { get; set; }
        public Decimal Tien0 { get; set; }
        public Decimal Tien_nt0 { get; set; }
        public Decimal Thue { get; set; }
        public Decimal Thue_nt { get; set; }
        public String Stt_rec { get; set; }
        public String Ma_gd { get; set; }
        public DateTime Ngay_ct { get; set; }
        public DateTime Ngay_lct { get; set; }
        public String So_seri { get; set; }
        public String So_ct { get; set; }
        public String So_lo { get; set; }
        public String So_lo1 { get; set; }
        public DateTime? Ngay_lo { get; set; }
        public String So_dh { get; set; }
        public String Ong_ba { get; set; }
        public String Dia_chi { get; set; }
        public String Ma_so_thue { get; set; }
        public String Ma_nx { get; set; }
        public Decimal T_so_luong { get; set; }
        public String Px_gia_dd { get; set; }
        public Decimal Ty_gia { get; set; }
        public Decimal T_tien_nt { get; set; }
        public Decimal T_tien { get; set; }
        public Decimal T_thue_nt { get; set; }
        public Decimal T_thue { get; set; }
        public Decimal Sua_thue { get; set; }
        public String Ma_kh2 { get; set; }
        public String Tk_thue_co { get; set; }
        public String Tk_thue_no { get; set; }
        public Decimal Sua_tkthue { get; set; }
        public Decimal T_tien_nt2 { get; set; }
        public Decimal T_tien2 { get; set; }
        public Decimal Tinh_ck { get; set; }
        public String Tk_ck { get; set; }
        public Decimal T_ck_nt { get; set; }
        public Decimal T_ck { get; set; }
        public Decimal Han_tt { get; set; }
        public Decimal T_tt_nt { get; set; }
        public Decimal T_tt { get; set; }
        public String Ten_vtthue { get; set; }
        public String Loai_ct { get; set; }
        public String So_lsx { get; set; }
        public String Ma_ku { get; set; }
        public Decimal Sua_tien { get; set; }
        public DateTime? Ngay_s1 { get; set; }
        public DateTime? Ngay_s2 { get; set; }
        public String Gc_s1 { get; set; }
        public String Gc_s2 { get; set; }
        public Decimal Sl_s1 { get; set; }
        public Decimal Sl_s2 { get; set; }
        public String Ma_s1 { get; set; }
        public String Ma_s2 { get; set; }
        public String Ma_tb { get; set; }
        public String Ma_hdm { get; set; }
        public String Ma_dvcs { get; set; }
        public Decimal Thue_ck0 { get; set; }
        public String Ma_px { get; set; }
        public Decimal Ty_giaf { get; set; }
        public String Ma_qs { get; set; }
        public String Ws_id { get; set; }
        public int Row_id { get; set; }
        public String Search { get; set; }
        public String Hd_thue { get; set; }
        public Int32 User_id { get; set; }
        public String Ma_thck { get; set; }
        public String Ghi_chu0 { get; set; }
        public String Ma_thue { get; set; }
        public Int32 Nv_duyet { get; set; }
        public DateTime? Han_giaohang { get; set; }
        public DateTime? Han_thanhtoan { get; set; }
        public String Dk_giaohang { get; set; }
        public String Dk_thanhtoan { get; set; }
        public String Chinhsach_ck { get; set; }
        public String Status_name { get; set; }
        public String Status_name2 { get; set; }
        public Decimal Du13 { get; set; }
        public String Nh_kh3 { get; set; }
        public String Ma_dvcs_bl { get; set; }
        public String Ten_kh { get; set; }
    }
}
